### ISSUE TITLE
some imports missing when building with --production

### ISSUE THREAD

**Issue by JanvanCasteren** [bsliran/angular2-meteor-base#107]
I have build a meteor-angular application based on https://github.com/Urigo/angular-meteor-base

It uses [ngx-md](https://www.npmjs.com/package/ngx-md), a Markdown module for angular. This module is dependent on [Marked](https://www.npmjs.com/package/marked), another npm module.

When I build my project in develop modus (the 'meteor' command) everythings runs fine. When I build with production flag (meteor --production) however, Markdown functionality is not working. It seems to me that the Marked module is not important.

I don't know how to solve this. Any tips?

**Comment by GuofuHuang** [comment]
I think I get a similar error, have you solved it?

**Comment by ardatan** [comment]
Thank you for contributing!
Boilerplate has been updated, if you have still the same error please feel free to open a new issue.
