### ISSUE TITLE
 Error: There is already a collection named "parties"

### ISSUE THREAD

**Issue by hayk94** [bsliran/angular2-meteor-base#25]
Hello guys I am following this tutorial. Everything was working fine for me till step 4.10. Now my app is not being built because of the error  Error: There is already a collection named "parties" . As I did some search I tried adding 

```
"compileOnSave": false,
  "buildOnSave": false 
```

But that doesn't fix the problem. Please help.

**Comment by bsliran** [comment]
hi, @hayk94, does the problem consists?
I just followed the tutorial by myself and everything seems to work fine.
can you give more details on the error?

**Comment by dschnelldavis** [comment]
I had the same problem, but finally found a solution, here:

http://stackoverflow.com/questions/37435358/a-method-named-parties-insert-is-already-defined-angular-meteor-tutorials/39029457#39029457
