### ISSUE TITLE
 {}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss not found in file

### ISSUE THREAD

**Issue by mmwo** [bsliran/angular2-meteor-base#26]
Tried to bootstrap app from boilerplate
When installing package and trying to import it's styles get the error

`While processing files with angular2-compilers (for target web.browser):
   /client/main.scss: Scss compiler error: File to import:
   {}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss not
   found in file: /home/skellige/ng2/snake/{}/client/main.scss`

Tried also on twiter bootstrap styles cannot be found in node_modules,
maybe its the error caused by not valid npm package downloaded returns:

**meteor npm install --save angular2-meteor-accounts-ui** 
npm WARN shrinkwrap Excluding devDependency: chai@3.5.0 { '@angular/common': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/compiler': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/core': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/forms': '0.2.0',
npm WARN shrinkwrap   '@angular/platform-browser': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/platform-browser-dynamic': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/router': '3.0.0-alpha.8',
npm WARN shrinkwrap   'angular2-meteor': '0.6.2',
npm WARN shrinkwrap   'angular2-meteor-accounts-ui': '^0.6.1',
npm WARN shrinkwrap   'angular2-meteor-auto-bootstrap': '0.6.0',
npm WARN shrinkwrap   'angular2-meteor-polyfills': '0.1.1',
npm WARN shrinkwrap   'angular2-meteor-tests-polyfills': '0.0.2',
npm WARN shrinkwrap   'es6-shim': '0.35.1',
npm WARN shrinkwrap   'meteor-node-stubs': '0.2.3',
npm WARN shrinkwrap   'reflect-metadata': '0.1.3',
npm WARN shrinkwrap   rxjs: '5.0.0-beta.6',
npm WARN shrinkwrap   'zone.js': '0.6.12' }
npm WARN shrinkwrap Excluding devDependency: chai-spies@0.7.1 { '@angular/common': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/compiler': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/core': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/forms': '0.2.0',
npm WARN shrinkwrap   '@angular/platform-browser': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/platform-browser-dynamic': '2.0.0-rc.4',
npm WARN shrinkwrap   '@angular/router': '3.0.0-alpha.8',
npm WARN shrinkwrap   'angular2-meteor': '0.6.2',
npm WARN shrinkwrap   'angular2-meteor-accounts-ui': '^0.6.1',
npm WARN shrinkwrap   'angular2-meteor-auto-bootstrap': '0.6.0',
npm WARN shrinkwrap   'angular2-meteor-polyfills': '0.1.1',
npm WARN shrinkwrap   'angular2-meteor-tests-polyfills': '0.0.2',
npm WARN shrinkwrap   'es6-shim': '0.35.1',
npm WARN shrinkwrap   'meteor-node-stubs': '0.2.3',
npm WARN shrinkwrap   'reflect-metadata': '0.1.3',
npm WARN shrinkwrap   rxjs: '5.0.0-beta.6',
npm WARN shrinkwrap   'zone.js': '0.6.12' }
angular2-meteor-base@ /home/skellige/ng2/snake
└── angular2-meteor-accounts-ui@0.6.1

**Comment by bsliran** [comment]
hi @Jitra 
I had problem importing both of the files,
can you check if the files actually exists inside the node modules in the correct path?

**Comment by mmwo** [comment]
Today I tried to clone your repository again, and downloaded both bootstrap and accounts UI packages and it works. I just had to restart meteor to import files

**Comment by remyacv83** [comment]
@Urigo , same error 
here is the project url:
https://github.com/remyacv83/angular2-meteor-sample

**Comment by Urigo** [comment]
@remyacv83 can you try a fresh clone with the updated repo?
