### ISSUE TITLE
Boilerplate not working with RC5

### ISSUE THREAD

**Issue by wtfuii** [bsliran/angular2-meteor-base#27]
If I'm bumping the Angular 2 depencies to RC5 and run `npm update`, the boilerplate throws a JS error in the browser after starting it with `meteor run`. The boilerplate should be compatible with the current version of Angular 2.

**Comment by ValentinFunk** [comment]
Just ran into the same thing, this is what happens: https://github.com/Urigo/angular2-meteor-auto-bootstrap/issues/22

**Comment by brackio** [comment]
Are there plans to update this boilerplate to angular RC5?
