### ISSUE TITLE
Step 0 - Bootstrapping  ,meteor   is  err

### ISSUE THREAD

**Issue by xiaofeihe** [bsliran/angular2-meteor-base#31]
Step 0 - Bootstrapping

 $ meteor npm install        ok: 
$ meteor
=> Started proxy.  
=> Started MongoDB.  
=> Errors prevented startup:                                                       

   While loading package barbatus:scss-compiler@3.8.1_1:
   error: Command failed: /home/sen/.meteor/packages/meteor-tool/.1.4.1_1.lcsnvf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --no-bin-links --update-binary
   { [Error: EACCES: permission denied, mkdir
   '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1xuiklv/node_modules/node-sass/vendor/linux-x64-46']
   errno: -13,
   code: 'EACCES',
   syscall: 'mkdir',
   path: '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1xuiklv/node_modules/node-sass/vendor/linux-x64-46' }
   gyp info it worked if it ends with ok
   gyp verb cli [ '/home/sen/.meteor/packages/meteor-tool/.1.4.1_1.lcsnvf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
   gyp verb cli   '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.4.0
   gyp info using node@4.5.0 | linux | x64
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp verb check python checking for Python executable "python2" in the PATH
   gyp verb `which` succeeded python2 /usr/bin/python2
   gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
   gyp verb get node dir no --target version specified, falling back to host node version: 4.5.0
   gyp verb command install [ '4.5.0' ]
   gyp verb install input version string "4.5.0"
   gyp verb install installing version: 4.5.0
   gyp verb install --ensure was passed, so won't reinstall if already installed
   gyp verb install version is already installed, need to check "installVersion"
   gyp verb got "installVersion" 9
   gyp verb needs "installVersion" 9
   gyp verb install version is good
   gyp verb get node dir target node version installed: 4.5.0
   gyp verb build dir attempting to create "build" dir:
   /home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1xuiklv/node_modules/node-sass/build
   gyp ERR! configure error 
   gyp ERR! stack Error: EACCES: permission denied, mkdir
   '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1xuiklv/node_modules/node-sass/build'
   gyp ERR! stack     at Error (native)
   gyp ERR! System Linux 4.4.0-36-generic
   gyp ERR! command "/home/sen/.meteor/packages/meteor-tool/.1.4.1_1.lcsnvf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext="
   "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
   gyp ERR! cwd /home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1xuiklv/node_modules/node-sass
   gyp ERR! node -v v4.5.0
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   Build failed

**Comment by derek-fong** [comment]
According to the error message

> [Error: EACCES: permission denied, mkdir
> '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.mubs29++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1xuiklv/node_modules/node-sass/vendor/linux-x64-46']

Can you please verify your folder permissions?

**Comment by xiaofeihe** [comment]
$ sudo  chown -R sen:sen ~/.meteor 

on app files
$ sudo   meteor  

`
sen@senpc:~/dev/lvapp$ sudo  chown -R sen:sen *
[sudo] sen 的密码： 
sen@senpc:~/dev/lvapp$ meteor 
[[[[[ ~/dev/lvapp ]]]]]                       

=> Started proxy.  
/home/sen/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: EACCES: permission denied, mkdir '/home/sen/dev/lvapp/.meteor/local'
    at Error (native)
sen@senpc:~/dev/lvapp$ sudo -s
root@senpc:~/dev/lvapp# meteor 
[[[[[ ~/dev/lvapp ]]]]]                       

=> Started proxy.  
=> Started MongoDB.  
=> Errors prevented startup:                  

   While loading package barbatus:scss-compiler@3.8.1_1:
   error: Command failed: /home/sen/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --no-bin-links --update-binary
   { [Error: EACCES: permission denied, mkdir
   '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.1iwvc59++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1ci2nis/node_modules/node-sass/vendor/linux-x64-46']
   errno: -13,
   code: 'EACCES',
   syscall: 'mkdir',
   path: '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.1iwvc59++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1ci2nis/node_modules/node-sass/vendor/linux-x64-46' }
   gyp info it worked if it ends with ok
   gyp verb cli [ '/home/sen/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
   gyp verb cli   '/home/sen/.meteor/packages/barbatus_scss-compiler/.3.8.1_1.1iwvc59++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]

`

**Comment by bsliran** [comment]
Hey, can you go ahead and ls -la inside the project folder?
another thing we could try to test, you could try and create the folder manually and see if you encounter the same permission problems

**Comment by dotansimha** [comment]
Please try again now, I also had some issues with the Meteor version we had here, and now it updated to the latest, which looks fine. 
Can you try? 

Please reopen if you still have issues.
