### ISSUE TITLE
Error while checking for angular2-compilers@0.6.1:

### ISSUE THREAD

**Issue by Tbutnyakov** [bsliran/angular2-meteor-base#32]
Hey!
I cloned this rep, and "meteor npm install" showed me error with 'typings i' installation. 
"**npm install -g typings**" solves this problem

But "**meteor**" - command display this error. 

```
Started MongoDB.
Errors prevented startup:

While checking for angular2-compilers@0.6.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

Your application has errors. Waiting for file change.
```

**Comment by hfournier** [comment]
I believe that should be angular2-meteor@0.6.2 instead.

**Comment by derek-fong** [comment]
@Tbutnyakov https://github.com/Urigo/angular2-meteor/issues/383

**Comment by Tbutnyakov** [comment]
@derek-fong thanks a lot!
