### ISSUE TITLE
Running on mobile (android) get "EXCEPTION: The selector "app" did not match any elements"

### ISSUE THREAD

**Issue by werber** [bsliran/angular2-meteor-base#35]
Didn't change anything from initial setup. Just did 
`git clone https://github.com/bsliran/angular2-meteor-base ang-2-test`
then 
`npm i`
then 
`meteor add-platform android`
and after that
`meteor run android`

And get output: 

> [[[[[ ~/ang-2-test ]]]]]                      
> 
> => Started proxy.  
> => Started MongoDB.  
> => Started your app.                          
> 
> => App running at: http://localhost:3000/  
> => Started app on Android Emulator.  
> I20160927-17:56:18.687(3)? 09-27 17:56:15.613 11815 11815 I chromium: [INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0, default verbosity = 0
> I20160927-17:56:18.893(3)? 09-27 17:56:15.618 11815 11815 W chromium: [WARNING:resource_bundle.cc(285)] locale_file_path.empty()
> I20160927-17:56:18.893(3)? 09-27 17:56:15.779 11815 11840 W chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
> I20160927-17:56:18.894(3)? 09-27 17:56:16.252 11815 11815 I MeteorWebApp: Serving asset bundle with version: 94dbac9ac7f82b0f10b6111dbf61355da9929c6a
> I20160927-17:56:19.453(3)? 09-27 17:56:19.207 11815 11815 I chromium: [INFO:CONSOLE(44719)] "EXCEPTION: The selector "app" did not match any elements", source: http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c (44719)
> I20160927-17:56:19.453(3)? 09-27 17:56:19.207 11815 11815 I chromium: [INFO:CONSOLE(44724)] "ORIGINAL STACKTRACE:", source: http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c (44724)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium: [INFO:CONSOLE(44725)] "Error: The selector "app" did not match any elements
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at DomRenderer.selectRootElement (http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:52929:27)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at AppView.selectOrCreateHostElement (http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:50698:45)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at AppView._View_AppComponent_Host0.createInternal (AppComponent_Host.ngfactory.js:12:21)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at AppView.create (http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:50676:25)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at ComponentFactory.create (http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:47286:40)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at ApplicationRef_.bootstrap (http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:48308:44)
> I20160927-17:56:19.454(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:48217:93
> I20160927-17:56:19.455(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at Array.forEach (native)
> I20160927-17:56:19.455(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at PlatformRef_._moduleDoBootstrap (http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:48217:46)
> I20160927-17:56:19.455(3)? 09-27 17:56:19.207 11815 11815 I chromium:     at http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c:48185:31", source: http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c (44725)
> I20160927-17:56:19.457(3)? 09-27 17:56:19.211 11815 11815 I chromium: [INFO:CONSOLE(22161)] "Unhandled Promise rejection:", source: http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c (22161)
> I20160927-17:56:19.457(3)? 09-27 17:56:19.211 11815 11815 I chromium: [INFO:CONSOLE(22163)] "Error: Uncaught (in promise): Error: The selector "app" did not match any elements", source: http://localhost:12664/packages/modules.js?hash=4be311643e1c41661f1a49112889b8bafe1ed68c (22163)

**Comment by dotansimha** [comment]
Yeah that's right... that's a bug. fixed in #37, will be merged soon.
