### ISSUE TITLE
Uncaught reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by mahesh0431** [bsliran/angular2-meteor-base#36]
Hi All,

I am trying to follow the steps from https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping  but facing few issues, initially i got the compiler issue, which i resolved from this thread https://github.com/derek-fong/angular2-meteor-boilerplate/issues/3#issuecomment-249904888.

Now i am getting another issue when i started the app using meteor command. Then in the browser local host, i got this error in the console:

**Uncaught reflect-metadata shim is required when using class decorators
DecoratorFactory    @   core.umd.js:403
(anonymous function)    @   app.component.ts:4
meteorInstall.client.app.component.js   @   app.component.ts:8
fileEvaluate    @   install.js:153
require @   install.js:82
(anonymous function)    @   main.ts:5**

can someone pls help me on this?

Best Regards,
Mahesh

**Comment by mahesh0431** [comment]
One more thing i have observed is that in the visual code editor, it is showing error at import statement as shown below
![image](https://cloud.githubusercontent.com/assets/6804552/18900713/02e19aca-8562-11e6-87a5-a485eb181a2a.png)

usually it shouldnt show any error as the path i have given is a correct one. Dont know if this is linked to the above issue.

**Comment by derek-fong** [comment]
@mahesh0431 try `meteor add barbatus:angular2-polyfills`to fix your "Uncaught reflect-metadata" issue. 

For for VS editor issue I am not sure how to fix that (I am using other IDEs) but I think your app should still run although it is showing this error.

**Comment by mahesh0431** [comment]
@derek-fong i've tried that and the issue is resolved but another issue is coming as shown below:

**Uncaught TypeError: Cannot read property 'bootstrap' of undefined
bootstrap   @   bootstrap.js:9
meteorInstall.client.main.js    @   main.ts:4
fileEvaluate    @   install.js:153
require @   install.js:82
(anonymous function)    @   main.ts:4**

in the bootstrap js file, at the line below, the MeteorApp object is undefined, so the error is coming:
**return angular2_meteor_1.MeteorApp.bootstrap(component, platform_browser_1.BROWSER_PLATFORM_PROVIDERS, [platform_browser_1.BROWSER_APP_PROVIDERS, platform_browser_dynamic_1.BROWSER_APP_COMPILER_PROVIDERS, angular2_meteor_1.METEOR_PROVIDERS], providers);**

Dont know why this many issues are coming, i am simply following the tutorial in angular-meteor website, not sure if i missed any step..

**Comment by derek-fong** [comment]
@mahesh0431 The [Angular2-meteor tutorial](https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping) is not up-to-date at the moment. `angular2-meteor-auto-bootstrap` is no longer required since `angular2 RC5`. 

Apart from that, there are also quite a few breaking changes (e.g. `NgModule`) since  `angular2 RC5` which unfortunately the tutorial has not been updated to reflect these changes. 

That being said, you can still read through the tutorial to try and understand the key concepts of `angular2-meteor`, use this repo as a starting point to your project and modify the code accordingly.

**Comment by mahesh0431** [comment]
Thanks @derek-fong , i guess the tutorial works with the older versions of angular2, i will wait till it gets update, meanwhile i will explore other things....

Thanks again @derek-fong for helping

Regards,
Mahesh
