### ISSUE TITLE
 I always get this and not that I can do. I work on Windows 10 64bit

### ISSUE THREAD

**Issue by ernestomr87** [bsliran/angular2-meteor-base#39]
E:\Projects\LearnMeteor\socially>meteor
[[[[[ ~\E\Projects\LearnMeteor\socially ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While checking for angular2-compilers@0.6.1:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it
   for your platform.

=> Your application has errors. Waiting for file change.

**Comment by kamilkisiela** [comment]
Try to open an issue [here](https://github.com/Urigo/angular-meteor/issues/new) :)
