### ISSUE TITLE
Unable to load sass file

### ISSUE THREAD

**Issue by ppoliani** [bsliran/angular2-meteor-base#43]
I have created a new component (`HomeComponent`) and try to inject the local `scss` file.

```
import template from './home.component.html';
import style from './home.component.scss';

@Component({
  selector: 'home',
  template,
  styles: [style]
})
```

However a get the following error. 

```
Uncaught Error: Expected 'styles' to be an array of strings.
```

It seems that the `scss` loader is unable to load the content of that file

**Comment by ppoliani** [comment]
I ended up doing the following hack to make it work

```
const style = require('./home.component.scss').innerText;

@Component({
  selector: 'home',
  template,
  styles: [style]
})
```

It is quite weird because I cannot reproduce it when I take a fresh clone of this repo.

**Comment by dotansimha** [comment]
That's one option, but please try now with the latest version of the boilerplate - I fixed the dependencies issue and it should solve your SCSS as well.

Please re-open if it still causing problems!

**Comment by ppoliani** [comment]
Thank you @dotansimha. Could you please tell which deps need to be updated. I am already using the the previous boilerplate and I can't start from scratch using the latest version. Is it easy to bring my current version to the state of the latest boilerplate?
