### ISSUE TITLE
Which module loader ... webpack, systemjs?

### ISSUE THREAD

**Issue by hakikihacioglu** [bsliran/angular2-meteor-base#48]
Hi,

I don't see any module loader like webpack or systemjs in the folders. Are you using another one, or am I missing something. I need a module loader for my project, How can I integrate webpack for example into this base-project?

Thank you

**Comment by dotansimha** [comment]
Hi @hakikihacioglu ,
Meteor base projects does not contain a "traditional" bundler such as Webpack.
However, Meteor has it's own implementation for CommonJS as modules loader, and uses it's own bundler and builder to build the project.
