### ISSUE TITLE
tsconfig.json doesn't include src files

### ISSUE THREAD

**Issue by anstarovoyt** [bsliran/angular2-meteor-base#50]
Hi. This commit https://github.com/Urigo/angular2-meteor-base/commit/ccb5346e7b96361e868f6ae80144c29fdfc39420#diff-e5e546dd2eb0351f813d63d1b39dbc48 added the files section:
files:[ "typings.d.ts"] 

and now tsconfig.json doesn't include all other project files.

**Comment by ijager** [comment]
Yes there's something strange with this section. 

For me it works fine in Meteor, but to satisfy VSCode I have to add at least one typescript file per directory to this `files` array. 

If I do not do that VSCode does not recognize imports and ExperimentalDecorators etc in files in that directory.

 I am even using the same typescript compiler from the Angular2-Compilers Meteor package..

**Comment by dotansimha** [comment]
I think that might be because of the typescript compiler that appends the files to the TypeScript compiler after Meteor done mapping the files that needs compilation. 
Can you try to add your files under `files` or `filesGlob` and then test again?

**Comment by kamilkisiela** [comment]
`files` doesn't cooperate with `exclude`. 

If we will use `exclude` it will look up for all `*.ts` files excluding these specified.
With `files` we provide files directly.

I will fix it in couple of minutes.
