### ISSUE TITLE
2 errors on typings.d.ts  with Atom and atom-typescript

### ISSUE THREAD

**Issue by Jakino** [bsliran/angular2-meteor-base#54]
ide:  ATOM 1.12.7
Package: atom-typescript 10.1.13
Os : ubuntu 16.10

file:  angular2-meteor-base/typings.d.ts 

**line 3**  `/// <reference types="@types/underscore" />`
**error**:  Cannot find type definition file for '@types/underscore'

**line 36** `stub(collection: Mongo.Collection);`
**error**: Generic type 'Collection<T>' requires 1 type argument(s)

my tsconfig.json

{
  "atom": {
    "rewriteTsconfig": true
  },
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "lib": [
      "es6",
      "dom"
    ],
    "emitDecoratorMetadata": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "files": [
    "both/collections/demo.collection.ts",
    "both/models/demo.model.ts",
    "client/imports/app/app.component.ts",
    "client/imports/app/app.module.ts",
    "client/imports/app/demo/demo-data.service.test.ts",
    "client/imports/app/demo/demo-data.service.ts",
    "client/imports/app/demo/demo.component.test.ts",
    "client/imports/app/demo/demo.component.ts",
    "client/imports/app/index.ts",
    "client/lib/init.test.ts",
    "client/main.ts",
    "server/imports/server-main/main.test.ts",
    "server/imports/server-main/main.ts",
    "server/main.ts",
    "typings.d.ts"
  ],
  "filesGlob": [
    "**/*.ts"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}

**Comment by dotansimha** [comment]
Fixed in the recent commit. please try with a clean copy of the repository, and make sure to reinstall node_modules.

**Comment by Jakino** [comment]
Ok it's fixed only one error  with the last commit.
I've deleted old folder and reinstaller with a new fresh git cloned repository for testing.
Now i get 2 other error messages:

**line 3** `/// <reference types="@types/underscore" />`
**error**: Cannot find type definition file for '@types/underscore'

**line 33**: `  import { Mongo } from "meteor/mongo";`
**error**: Cannot find module 'meteor/mongo'

**Comment by Urigo** [comment]
@Jakino can you open on a new issue?

**Comment by Jakino** [comment]
https://github.com/Urigo/angular2-meteor-base/issues/56
