### ISSUE TITLE
dispatch:mocha-phantomjs package is now unmaintained 

### ISSUE THREAD

**Issue by mo2menelzeiny** [bsliran/angular2-meteor-base#61]
while updating the package I encountered an error which lead me to their GitHub repo, which was moved to the maintained package dispatch:mocha on the following repo https://github.com/DispatchMe/meteor-mocha, consider updating the Meteor package in the dependencies.

**Comment by ardatan** [comment]
I am not sure about your issue, but dispatch:mocha-phantomjs has old versions of dependencies, so you need to update your test drivers to ardatan:mocha.
You can look at the example below;
https://github.com/Urigo/angular-meteor/tree/master/tests/angular-compilers-tests
If the issue isn't solved, you can open a new issue.
