### ISSUE TITLE
What generator to use for creating modules

### ISSUE THREAD

**Issue by louiealmeda** [bsliran/angular2-meteor-base#65]
I tried using angular cli to create a component and it is not compatible with the file structure here. And is generating a different way of testing. 
What cli should I use on generating components for this project? 

Thanks

**Comment by darkbasic** [comment]
We're already working on an updated angular2-meteor-base, it will get released with sample tests.

**Comment by Urigo** [comment]
@louiealmeda that depends if you want to use the Angular CLI or the Meteor CLI.

Meteor CLI doesn't have the capability currently to generate components, so if you prefer to use the Angular CLI, check out the example app here: https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor

I'm not sure if generating component is such an important feature but I can understand the need.

In terms of testing, we've improved that aspect a lot so you will be able to see new tests on this repo by the end of this day, and you can also already check testing examples here:

For Meteor CLI:
https://github.com/Urigo/angular-meteor/blob/master/tests/angular-compilers-tests/client/imports/app/app.component.spec.ts

For Angular CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor/e2e
and https://github.com/Urigo/angular-meteor/blob/master/examples/angularcli-meteor/src/app/app.component.spec.ts
