### ISSUE TITLE
Test config

### ISSUE THREAD

**Issue by GuofuHuang** [bsliran/angular2-meteor-base#68]
The documentation says it has test configuration, but it is not, need to be solved.

**Comment by ardatan** [comment]
I've added tests, you can check it out now.

**Comment by GuofuHuang** [comment]
I have tried it, it passes all test, but it shows crash message like this: "Your app is crashing. Here's the latest log", is that normal?

**Comment by ardatan** [comment]
Mocha package gives that error in watch mode. I am still working on it, but if it passes, it is ok for your code.
