### ISSUE TITLE
meteor 1.6 not working

### ISSUE THREAD

**Issue by papinaser** [bsliran/angular2-meteor-base#69]
Hi
I'm using your template with angular 4 and meteor 1.6 but it doesn't work for me.
When I run meteor command, project is compile well and is ready to browse http://localhost:3000,
but when I browse it my page is crash and I don't see any thing, I try to solve my problem and I found that when main.html is process and reaches to <app></app> tag The Application is crash.
please help me.

**Comment by papinaser** [comment]
Hi. please help me, my problem is that when I use angular 4 in my meteor application the application hangs or freezes.
please help me.

**Comment by ardatan** [comment]
I think it is the path problem on Windows, we've fixed that issue.
You can check it out new release.

**Comment by papinaser** [comment]
I search more and find another angular-meteor base project in [https://github.com/Urigo/angular-meteor](url) , I download and use it. it's good and I can use it without any problem.
Thank you.

**Comment by papinaser** [comment]
I search more and find another angular-meteor base project in https://github.com/Urigo/angular-meteor , I download and use it. it's good and I can use it without any problem.
Thank you.
