### ISSUE TITLE
can not run normaly

### ISSUE THREAD

**Issue by 1zhuzhiqiang1** [bsliran/angular2-meteor-base#72]
yestody is well , but when you update tody, run meteor is correct, but http://localhost:3000 can not load

**Comment by ardatan** [comment]
Could you give more details? trace, log etc...

**Comment by NPColdpage** [comment]
same here, chrome won't load the page and nothing in the console log. no error after run command **meteor**, it even crash my chrome for several time, but the most wired thing is it does work on my cloud centos machine lol. All same version of **angular-meteor-base**.

**Comment by ardatan** [comment]
Could you give more details? Which OS/Enviroment?

**Comment by NPColdpage** [comment]
my ECS is Ali  in Cloud, centos 7.4 64 bit, it works pretty well, just test it now. And the local one is a windows 10 pro 64bits, it doesn't works. Like zhuzhiqiang said, it cannot load the page for some reason

**Comment by 1zhuzhiqiang1** [comment]
mac os is well, but win10 is bad

**Comment by ardatan** [comment]
Have you tried to update packages using;
`meteor update --all-packages`

**Comment by NPColdpage** [comment]
it works **meteor update --all-packages**
