### ISSUE TITLE
how do i type the correct source path for html to load the image? 

### ISSUE THREAD

**Issue by NPColdpage** [bsliran/angular2-meteor-base#73]
This is stupid, but I am having problem to load local images into my html files. I am using a centos machine, and run it as my server. the images are in the same directory of  the XXX.html, so my **src="XXX.png"**, but it won't load for some reason. When i inspect element, I saw the path is **<IP Address>:3000/XXX.png**, anybody know how to write the correct path.

**Comment by ardatan** [comment]
You have to copy your static files into public folder. Please check the Meteor documentation;
https://guide.meteor.com/structure.html

**Comment by NPColdpage** [comment]
Thank you so much!!!


public

All files inside a top-level directory called public/ are served as-is to the client. When referencing these assets, do not include public/ in the URL, write the URL as if they were all in the top level. For example, reference public/bg.png as <img src='/.png' />. This is the best place for favicon.ico, robots.txt, and similar files.

**Comment by ardatan** [comment]
You're welcome, this is what public for 👍
