### ISSUE TITLE
Can't import html file

### ISSUE THREAD

**Issue by GuofuHuang** [bsliran/angular2-meteor-base#74]
In this version, I find out that it can't import html files as it used to be, what package is needed to achieve that?

**Comment by GuofuHuang** [comment]
In the previous version, I can do this:
import template from './example.html';

but now it can't

**Comment by NPColdpage** [comment]
For your example.component.ts,  **templateUrl: 'example.html',** without slash, do you import in the app.module.ts ?

**Comment by GuofuHuang** [comment]
Yes, I just wander how can I import the html file as a string like it used to be. I'm OK with the templateUrl method, but would prefer the way I did before.

**Comment by Gcchao** [comment]
try to import file from **public** folder ?

**Comment by ardatan** [comment]
Importing html is not legal way to get html as string, so it was removed. If you still want to import html, you can move it to public folder , then fetch it by using XHR/AJAX.

**Comment by ardatan** [comment]
Issue will be closed
