### ISSUE TITLE
error for build

### ISSUE THREAD

**Issue by NPColdpage** [bsliran/angular2-meteor-base#76]
I am trying to build the package for server 

**# for example if deploying to a Ubuntu linux server:
npm install --production
meteor build /path/to/build --architecture os.linux.x86_64**

but it have error 

Errors prevented bundling:
While processing files with angular-compilers (for target web.browser):
C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass\lib\index.js:439:16: File to read not found or
unreadable: C:/Users/chao.geng/Desktop/website/csbiochina/C:/Users/chao.geng/Desktop/website/csbiochina/client/imports/app/todo-list/todo-list.scss
at Object.module.exports.renderSync
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass\lib\index.js:439:16)
at Function.compileFile (packages/angular-scss-compiler/index.js:19:17)
at TsCompilerAotCompilerTypeCheckHostAdapter.compiler._host.loadResource.filePath (packages/angular-typescript-compiler/index.js:317:38)
at Object.get
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler_factory.js:78:306)at DirectiveNormalizer._fetch
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:95:7)
at
C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:292:36
at Array.map (<anonymous>)
at DirectiveNormalizer._loadMissingExternalStylesheets
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:291:14)at DirectiveNormalizer._normalizeTemplateMetadata
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:201:7)
at
C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:127:7
at Object.then
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\util.js:164:3)
at DirectiveNormalizer.normalizeTemplate
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:127:7)
at CompileMetadataResolver.loadDirectiveMetadata
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\metadata_resolver.js:361:44)
at
C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\metadata_resolver.js:614:54
at Array.forEach (<anonymous>)
at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\metadata_resolver.js:613:16)
at C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler.js:91:7
at Array.map (<anonymous>)
at AotCompiler.analyzeModulesAsync
(C:\Users\chao.geng\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler.js:91:7)
at Promise.asyncApply (packages/angular-typescript-compiler/index.js:332:42)
at C:\Users\chao.geng\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40

**Comment by ardatan** [comment]
Do you have that file on the path;
C:/Users/chao.geng/Desktop/website/csbiochina/client/imports/app/todo-list/todo-list.scss

**Comment by NPColdpage** [comment]
Yes, for some reason, I can successfully build the tar file from my Linux machine, but for my windows, it doesn't work

**Comment by Slavrix** [comment]
C:/Users/chao.geng/Desktop/website/csbiochina/C:/Users/chao.geng/Desktop/website/csbiochina/client/imports/app/todo-list/todo-list.scss

as can be seen in this line, the file doesn't exist as for some reason on windows it is adding the first section of the path twice.

styleUrls: ['./todo-list.scss'] im assuming your using a line like this in the component.

**Comment by fidelsam1992** [comment]
It was solved with me upgrading the versions of those packages : 
in the versions file
angular-compilers@0.2.9_2
angular-html-compiler@0.2.9
angular-scss-compiler@0.2.9
angular-typescript-compiler@0.2.9_5
