### ISSUE TITLE
Cannot set base providers because it has already been called

### ISSUE THREAD

**Issue by GuofuHuang** [bsliran/angular2-meteor-base#80]
When I try to setup the test environment like this:

    TestBed.initTestEnvironment(
      BrowserDynamicTestingModule,
      platformBrowserDynamicTesting()
    );
it gives me the error:
Cannot set base providers because it has already been called

any ideas to solve it?

**Comment by hassan-kassim** [comment]
Hi GuofuHuang,

i face this same issue can you let me know how u fix this issue!!!
