### ISSUE TITLE
Max call stack exceed

### ISSUE THREAD

**Issue by mbtechnologyil** [bsliran/angular2-meteor-base#87]
my browser is getting stuck then after few seconds getting "stack exceed"
all i did is:
1 . Clone repository
2. npm install
3. npm run start

No errors on CLI

**Comment by maxfriedmann** [comment]
Are you on windows by any chance? See https://github.com/Urigo/angular-meteor/issues/1749#issuecomment-347235040

**Comment by ardatan** [comment]
Thank you for contributing!
Boilerplate has been updated, if you have still the same error please feel free to open a new issue.
