### ISSUE TITLE
readme documents build command... but no build command exists in package.json

### ISSUE THREAD

**Issue by nhhockeyplayer** [bsliran/angular2-meteor-base#97]
readme documents build command... but no build command exists in package.json

to what extent is new interest to determine what does what

any attempts to build using angular-cli fail

how to build
cannot build
product also hangs on meteor run

**Comment by nhhockeyplayer** [comment]
build output from command shell as administrator

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base>meteor npm i
npm ERR! path C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base\node_modules\fsevents\node_
modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base\node_modules\fsevents\no
de_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\git\\meteor\\angular-meteor-base\\node_modu
les\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\apache-tomcat-9.0.0.M17\\webapps\\ROOT\\git\\meteor\\angular-meteor-base\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2018-01-17T10_50_15_379Z-debug.log

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base>

**Comment by nhhockeyplayer** [comment]
Ok got as far as bootstrap process...

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base>meteor
[[[[[ C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base ]]]]]

=> Started proxy.
=> A patch (Meteor 1.6.0.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
[client]: ES2015 modules Compilation: 220936.146ms
[client]: TypeScript Files Compilation: 17331.202ms
[server]: ES2015 modules Compilation: 946.587ms
[server]: TypeScript Files Compilation: 7052.709ms
   Starting your app                         |

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

**Comment by nhhockeyplayer** [comment]
first attempt to navigate localhost:3000

produced console log msgs

{ Error: EPERM: operation not permitted, unlink 'C:\Users\owner\AppData\Local\Temp\mt-1fqpys9.8meu\npm\node_modules\ajv'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\owner\\AppData\\Local\\Temp\\mt-1fqpys9.8meu\\npm\\node_modules\\ajv' }
{ Error: EPERM: operation not permitted, unlink 'C:\Users\owner\AppData\Local\Temp\mt-6l54qs.ln2yt\npm\node_modules\buffer'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\owner\\AppData\\Local\\Temp\\mt-6l54qs.ln2yt\\npm\\node_modules\\buffer' }


and upon navigating to browser chrome says Ah Snap cannot navigate to page after it sits blank for a bit

still trying to shake this out

will try patch

**Comment by nhhockeyplayer** [comment]
I dont understand why

https://www.meteor.com/tutorials/angular/templates

refers to angular 1 KIND module code

?

**Comment by nhhockeyplayer** [comment]
unable to run app
refuses to launch from localhost:3000

using windows 7

this is console output

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base>meteor
[[[[[ C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor\angular-meteor-base ]]]]]

=> Started proxy.
[client]: ES2015 modules Compilation: 138306.225ms
[client]: TypeScript Files Compilation: 35.490ms
[server]: ES2015 modules Compilation: 1058.690ms
[server]: TypeScript Files Compilation: 27.109ms
Error starting Mongo (2 tries left): failed to connect to server [127.0.0.1:3001] on first connect [MongoError: connection 0 to 127.0.0.1:3001 timed
out]
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

**Comment by nhhockeyplayer** [comment]
regardless, I am unable to rectify these issues not knowing WHAT canned npm build commands are built into this meteor product when they are not even runnable as the readme states

at this point its guesswork

and I need to rework this app to get is resolved

cannot do without build commands

this is the issue...
npm is wrapped
angular-cli is wrapped
and we are limited to what meteor defines under the hood for this

currently cannot build or run this boiler plate repo app

assistance appreciated

**Comment by nhhockeyplayer** [comment]
well the meteor create --example blahblah 
command isnt ready for usage

it just says clone whatever and go with whats on github

i have commercial clients interested in using this object broker
and would like to take advantage angular5

can this be tightened up and resolved so field ops can proceed?

for angular2-5
currently there is
   o   no build support
   o   no create example project support
   o   app fails to run
   o   cannot rectify any issues given the lack of the above
   o   meteor wraps npm and angular-cli  and I am stuck locked with what meteor has defined thats not ready

help please.... thanks

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor>meteor create --list
Available examples:
  clock: https://github.com/meteor/clock
  leaderboard: https://github.com/meteor/leaderboard
  localmarket: https://github.com/meteor/localmarket
  simple-todos: https://github.com/meteor/simple-todos
  simple-todos-react: https://github.com/meteor/simple-todos-react
  simple-todos-angular: https://github.com/meteor/simple-todos-angular
  todos: https://github.com/meteor/todos
  todos-react: https://github.com/meteor/todos#react
  angular2-boilerplate: https://github.com/bsliran/angular2-meteor-base

To create an example, simply git clone the relevant repository and branch (run 'meteor create --example <name>'  to see the full command)

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor>meteor create --example angular2-boilerplate
To create the angular2-boilerplate example, please run:
  git clone https://github.com/bsliran/angular2-meteor-base

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\git\meteor>

**Comment by nhhockeyplayer** [comment]
you have a nice framework...
I was impressed with the language theory... stateful pub/sub
but this has been out for few years now and rightfully should be air tight at this point

my advice

leave the a1 legacy in the dust and get the a5 on deck air tight...first... so the field can proceed
make a5 the default for project for template for everything
and win

advice please on any solution or update...
cant do anything just sitting here waiting

**Comment by ardatan** [comment]
Thank you for contributing!
Boilerplate has been updated, if you have still the same error please feel free to open a new issue.
