### ISSUE TITLE
archetype project/app generator incomplete

### ISSUE THREAD

**Issue by nhhockeyplayer** [bsliran/angular2-meteor-base#98]
using meteor-1.6.0.1

when generating a app/project (using meteor archetype)

meteor create myapp

the package.json has no build commands centric to meteor
yet meteor wraps npm and angular-cli ?
we are left guessing what will work with meteor

these newly generated apps should be thoroughly cultivated with all sorts of npm build commands that meteor will accept

apps currently not runnable as of yet with this user

**Comment by ardatan** [comment]
Thank you for contributing!
Boilerplate has been updated, if you have still the same error please feel free to open a new issue.
